name: LUnix NG Kernel+APS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make devel
      run: make devel
    - name: make kernel for C64 
      run: make binaries MACHINE=c64
    - name: make apps for C64
      run: make apps
    - name: cleanup after C64
      run: make clean
    - name: make kernel for C128
      run: make binaries MACHINE=c128
    - name: make apps for C128
      run: make apps
    - name: cleanup after C128
      run: make clean
    - name: make kernel for atari
      run: make binaries MACHINE=atari
